20221128_13:16:10

diff --git a/.config/zsh/aliases b/.config/zsh/aliases
--- a/.config/zsh/aliases
+++ b/.config/zsh/aliases
@@ -226,52 +226,67 @@ then
   alias wimp='curl https://wttr.in/imperia'
 fi
 
-checkmd5() {
-  if [ command -v md5sum &> /dev/null ]
+checkSum () {
+  echo $1
+  echo $2
+  echo $3
+  if [ $1 = "" ] || [ $2 = "" ] || [ $3 = "" ]
   then
-    if [ [ $1 = "" ] || [ $2 = "" ] ]
+    echo "Usage: checkmd5 [md5|sha1|sha256|sha512] [file] [sum]"
+    return 2
+  fi
+  if ! [ $1 = "md5" ] || [ $1 = "sha1" ] || [ $1 = "sha256" ] || [ $1 = "sha512" ]
+  then
+    echo "algorithm (firt paramater) must be [md5|sha1|sha256|sha512]"
+    return 3
+  fi
+  local command="${1}sum"
+  if command -v $command &> /dev/null 
+  then
+    local sum=$($command $2 | cut -d ' ' -f 1)
+    echo $command
+    echo $sum
+    if [ $sum = $3 ]
     then
-      echo "Usage: checkmd5 [file] [md5sum]"
+      echo "${command} OK"
+      return 0
+    else
+      echo "${command} NOT OK!!"
       return 1
     fi
-    md5=$(md5sum $1)
-    if [ $md5 = $2 ]
-    then
-      echo "MD5 OK"
-    else
-      echo "MD5 NOT OK!!"
-    fi
+  echo "Command ${command} is not installed."
+  return 4
   fi
 }
 
-
-if [ $( command -v fzf ) ] && [ $( command -v rg ) ] ; then
+if [ $( command -v fzf ) ] && [ $( command -v rg ) && [ $( command -v bat ) ] ; then
   export FZF_BASE=/usr/bin/fzf
-  export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden '
+  export FZF_DEFAULT_COMMAND='rg --ignore-case --files --no-ignore-vcs --hidden '
   # catppucin theme
   # export FZF_DEFAULT_OPTS=' \
-    # --preview "bat --color=always --style=numbers --line-range=:500 {} \
+    # --preview bat --border=rounded  \
     # --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
     # --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
     # --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"'
   # aliasG fzfb="fzf \
-    # --preview "bat --color=always --style=numbers --line-range=:500 {} \
+    # --preview bat --border=rounded  \
     # --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
     # --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
     # --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
     # ; "
   # dracula theme
-  export FZF_DEFAULT_OPTS='\
-    --preview bat --color=always --style=numbers --line-range=:500 {} \
+  export FZF_DEFAULT_OPTS="\
+    --preview bat --border=rounded  \
     --color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 \
     --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 \
     --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 \
     --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4 \
-    ;'
+    ;"
   DISABLE_FZF_AUTO_COMPLETION="false"
   DISABLE_FZF_KEY_BINDINGS="true"
   aliasG fzfb="fzf \
-    --preview bat --color=always --style=numbers --line-range=:500 {} \
+    # --preview bat --color=always --style=numbers --line-range=:500 {} \
+    --preview bat --border=rounded  \
     --color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 \
     --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 \
     --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 \
@@ -279,5 +294,5 @@ if [ $( command -v fzf ) ] && [ $( command -v rg ) ] ; then
     ;"
   aliasG R='| rg '
 else
-  echo "fzf or rg are missing..."
+  echo "fzf|rg|bat missing..."
 fi
