20230914_20:38:29

diff --git a/.config/zsh/functions/fzf-fd-edit b/.config/zsh/functions/fzf-fd-edit
--- a/.config/zsh/functions/fzf-fd-edit
+++ b/.config/zsh/functions/fzf-fd-edit
@@ -23,6 +23,16 @@ has() {
   which "$@" > /dev/null 2>&1
 }
 
+# Check if ripgrep is installed
+if ! has fd; then
+  fail "Can't find fd - install fd-find and try again."
+fi
+
+# Check if fzf is installed
+if ! has fzf; then
+  fail "Can't find fzf - install fzf and try again."
+fi
+
 # If bat is installed, use bat for file previews
 if has bat; then
   fd-find-edit() {
diff --git a/.config/zsh/functions/fzf-rg-edit b/.config/zsh/functions/fzf-rg-edit
--- a/.config/zsh/functions/fzf-rg-edit
+++ b/.config/zsh/functions/fzf-rg-edit
@@ -26,6 +26,11 @@ if ! has rg; then
   fail "Can't find rg - install ripgrep and try again."
 fi
 
+# Check if fzf is installed
+if ! has fzf; then
+  fail "Can't find fzf - install fzf and try again."
+fi
+
 # Define the main function of the script
 fzf-rg-edit(){
   # Check for help flag
